### ISSUE TITLE
node version

### ISSUE THREAD

**Issue by stocksp** [pors/reactionic-kitchensink#14]
Will node versions above 4.3.1 be a problem?
I'm running 5.5.0...

**Comment by stocksp** [comment]
Didn't realize how easy nvm is to use ... and install the versions you require.

**Comment by pors** [comment]
@stocksp it should be able to run with higher versions of node. Did you try 5.5.0?

**Comment by stocksp** [comment]
No, I didn't  try ...  I did have issues with Meteor and its ancient version of node in the past (on Ubuntu deployment)... and went 'oh no ... not again' when I saw your version was different than my working version.
I just made friends with nvm ... so switching to the versions you have was easy,  at least on the Mac.
Very excited about react-ionic and Meteor ... thanks for your work!

**Comment by pors** [comment]
Yeah nvm is awesome, should be part of npm really.
