### ISSUE TITLE
error on IOS Simulator

### ISSUE THREAD

**Issue by stocksp** [pors/reactionic-kitchensink#15]
The Web app runs fine.  But when run in the Simulator I get the errors below in the console.   The Simulator does run fine  but the server is down....

reactionicKitchen cd app
➜  app meteor run
[[[[[ ~/projects/reactionicKitchen/app ]]]]]  

=> Started proxy.  
=> Started MongoDB.  
=> Started your app.                          

=> App running at: http://localhost:3000/  
^C    **<----- me stopping the server**  
➜  app meteor run ios
[[[[[ ~/projects/reactionicKitchen/app ]]]]]  

=> Started proxy.  
=> Started MongoDB.  
=> Started your app.                                                               

=> App running at: http://localhost:3000/  
=> Started app on iOS Simulator.  
{ [Error: UNKNOWN, unknown error '/private/var/folders/5g/5d_ngcg9341440n3bw2ld6380000gn/T/cordova-template-tppxhu']
  errno: -1,
  code: 'UNKNOWN',
  path: '/private/var/folders/5g/5d_ngcg9341440n3bw2ld6380000gn/T/cordova-template-tppxhu',
  syscall: 'readdir' }

/Users/paul/.meteor/packages/fourseven_scss/.3.4.3.1shl2zr++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
Error: UNKNOWN, open '/Users/paul/projects/reactionicKitchen/app/node_modules/fbjs/lib/emptyObject.js'
➜  app

**Comment by gabrielseco** [comment]
I looked into this issue and it gave me an error too.

`  While running Cordova app for platform iOS with options --emulator:
   Error: Command failed:
   /Users/gabriel/reactionic-kitchensink/app/.meteor/local/cordova-build/platforms/ios/cordova/run
   --emulator
   ENOENT, no such file or directory
   '/Users/gabriel/Library/Logs/CoreSimulator/5D305F03-5DDE-40CC-9ABE-E4CEDFCB4D10/system.log'
   at ChildProcess.exitCallback (/tools/utils/processes.js:151:23)
   at ChildProcess.emit (events.js:98:17)
   at Process.ChildProcess._handle.onexit (child_process.js:820:12)

/Users/gabriel/.meteor/packages/fourseven_scss/.3.4.3.m3q1mw++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
ExitWithCode:1`

# Solution

After doing meteor run ios, go to app/.meteor/local/cordova-build/platforms/ios

Then click in Reactionic.xcodeproj.

It'll open an xcode project, run it from there and you have your app running inside the simulator.

Tell me if it works for you.

I'll attach an image so you can see it.

![simulator screen shot 6 may 2016 0 02 35](https://cloud.githubusercontent.com/assets/7215480/15058687/f76afea4-131d-11e6-86c5-c8d7faea3859.png)

**Comment by stocksp** [comment]
I'm confused here.    The app is running fine in the  IOS simulator (for me).   It's the Meteor Server that has crashed.   The example project doesn't actually use the server to get any data (which is another issue for a demo) so it appears to be running fine...
??

**Comment by gabrielseco** [comment]
Ups... I didn't understand well the problem before

**Comment by pors** [comment]
I can't reproduce this. It works fine for me.

What version are you on?

Try removing all node_modules/\* and do `npm i` again to see it that helps.

Also try: `rm -Rf .meteor/local`

**Comment by stocksp** [comment]
Well good news!   It works now.   I just removed everything and downloaded the zip .....
sorry for all the noise...
@pors could I trouble you with one question?
The hyper link in 'about' that links to your website is not functional in the simulator but is when run as a web app ... is this 'just how it works' (or doesn't) in the IOS Simulator?

**Comment by pors** [comment]
@stocksp yeah I noticed the same in the popover. Somehow we want that the app opens an external browser. I found a couple of solutions here: http://stackoverflow.com/questions/10244965/phonegap-opening-external-urls-in-safari/15240429

If anyone would like to try them I'll create a generic solution.

**Comment by gabrielseco** [comment]
I did an example of external link here.

It needs cordova-inappbrowser to work.

I did a component 
https://github.com/gabrielseco/external-link/blob/master/app/client/imports/components/CordovaLink.js

Then I applied to the about.jsx

https://github.com/gabrielseco/external-link/blob/master/app/client/imports/components/about.jsx

I tested it in the browser, ios simulator and my iphone.

**Comment by stocksp** [comment]
@gabrielseco thank you! very helpful!
