### ISSUE TITLE
Problem when updating meteor

### ISSUE THREAD

**Issue by ThomasDebrunner** [pors/reactionic-kitchensink#18]
When updating meteor to `1.3.4.1` and try to launch the app, I get the following error:

```
=> Errors prevented startup:

   While processing files with fourseven:scss (for target web.browser):
   /client/styles/app.scss: Scss compiler error: Object [object Object] has no method 'existsSync'
```

**Comment by zuizuihao** [comment]
+1 have you solved that?

**Comment by ThomasDebrunner** [comment]
No, I just made my own kitchensink app with a newer Meteor version along with ES6. See here:
https://github.com/najiji/Meteor-React-Ionic-ES6-kitchensink

Would be nice to see a solution to original problem though.

**Comment by ghost** [comment]
+1 have the same problem

**Comment by pors** [comment]
I can't reproduce this. I run 1.3.4.4 and fourseven:scss 3.8.0.1

What sometimes helps is to uninstall and reinstall fourseven:scss.

**Comment by primeminister** [comment]
I had the issue too. Fixed it by prefixing the reactionic.scss reference with {}:

OLD: `@import '../../../node_modules/reactionic/dist/scss/styles/_reactionic.scss';`
NEW: `@import '{}/node_modules/reactionic/dist/scss/styles/_reactionic.scss';`

**Comment by pors** [comment]
@primeminister cool, can you provide a PR for the kitchensink then?

**Comment by primeminister** [comment]
Created new branch, but unfortunately Meteor upgrade of another app has screwed up my other apps, like kitchensink. So cannot update to latest meteor to test. @pors can you try?

**Comment by gabrielseco** [comment]
Webpack. Found a workaround, but breaks meteor.
See issue #24
