### ISSUE TITLE
"Errors prevented startup"

### ISSUE THREAD

**Issue by derekbtw** [pors/reactionic-kitchensink#2]
C:\Users\User\Desktop\reactionic-kitchensink\app>meteor run
[[[[[ C:\Users\User\Desktop\reactionic-kitchensink\app ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Errors prevented startup:

   While checking for mrt:redis@0.1.3:
   error: No compatible binary build found for this package. Contact the
   package author and ask them to publish it for your platform.

=> Your application has errors. Waiting for file change.

**Comment by pors** [comment]
That module shouldn't be in there :)

Should be fixed now. Thanks for bringing this up Derek!

**Comment by derekbtw** [comment]
Thanks! And you're welcome!
