### ISSUE TITLE
Is React-Ionic still supported?

### ISSUE THREAD

**Issue by JWPapi** [pors/reactionic-kitchensink#21]
I know you are checking your issues, so im asking here. Do you know if react-ionic is still supported? The latest update is about 40 days old. Im not sure if the framework is still maintained. Have you thought about taking it over?

**Comment by pors** [comment]
It is still supported. We have four maintainers, but I am very busy lately, and I know that one of the other maintainers is offline for a long holiday.

Is there a specific issue that blocks you? Please provide a pull request if you are in a hurry and I'll look into it.

Cheers
