### ISSUE TITLE
Cannot read property 'headerTitle' of undefined

### ISSUE THREAD

**Issue by giggioz** [pors/reactionic-kitchensink#22]
download the zip file

cd reactionic-kitchensink
npm install
cd app
meteor run

i got an error, in app.js look for
`title: currentPageProps.headerTitle`

using
node v4.3.1
npm v3.10.5
Meteor 1.3.2.4

**Comment by gabrielseco** [comment]
In the file clients/imports/components/layouts/main.jsx.

In the render method

Replace the next line

```
var currentPageProps = this.getPageProps(this.props.children.props.route.path);
```

with this

```
var currentPageProps = this.getPageProps(this.context.location.pathname);
```

**Comment by giggioz** [comment]
It works!
Thanks.

**Comment by pors** [comment]
@gabrielseco cool! Reverted the commit, thx
