### ISSUE TITLE
Router PropTypes Call is not correct

### ISSUE THREAD

**Issue by JWPapi** [pors/reactionic-kitchensink#25]
Im pretty sure the Router wont work for React 0.16 , because of:

https://facebook.github.io/react/warnings/dont-call-proptypes.html

I have updated a project to 0.15.3 with a similar router structure and Im getting the warnings, tomorrow or on sunday ill fix it anyway. but if someone knows how do it, He can fix it. Im an beginner coder, so ill probably need a bit.

To reproduce the warning, just update to 0.15.3 react!

**Comment by gabrielseco** [comment]
That occured to me using 0.15.2,  reinstalling the packages solve the issue for me, I'll try  updating with 0.15.3 and see if I catch the error.

**Comment by JWPapi** [comment]
Anyway im pretty sure its a correct warning since router is calling proptypes as far as i understand

**Comment by JWPapi** [comment]
My fault npm update or maybe deleting node modules npm install does the job. Its nothing wrong in here.
