### ISSUE TITLE
Run on window very slow

### ISSUE THREAD

**Issue by ltntamdev** [pors/reactionic-kitchensink#5]
Hi Pros,

I try run "meteor run" on window 7 64 bit, it go to download and update meteor to version 1.3-rc.10. I wait about 3 hours but it still downloading. Can you give a advice for me ?

Thanks

**Comment by pors** [comment]
I think they had issues with their downloads yesterday at MDG. I had the same, super slow downloads.
If it still didn't complete try to update to version 1.3, it is available now.

**Comment by ltntamdev** [comment]
Yes, I will update to version 1.3 and try again. Thanks
